language: ruby
services:
  - postgresql
env:
  global:
    - COVERALLS_PARALLEL=true
    - RAILS_ENV=test
    - RUBYOPT=-W0
rvm:
  - 2.3.8
script:
  - bundle exec rake parallel:setup
  - bundle exec rake parallel:test
  # - bundle exec rake db:setup 
  # - bundle exec rake db:fixtures:load
  # - bundle exec rake test
before_script:
  - cp config/configuration.yml.dist config/configuration.yml
  - cp config/database.yml.travis config/database.yml
  - cp config/application.yml.dist config/application.yml
  - cp config/mailers.yml.dist config/mailers.yml 
  - cp config/secrets.yml.dist config/secrets.yml 
  - psql -c 'create database befdata_test;' -U postgres
  - bin/delayed_job_testing start
notifications:
  webhooks: https://coveralls.io/webhook
